run:
  timeout: 5m
  issues-exit-code: 1
  skip-dirs:
    - docs

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-same-issues: 0

