name: CI

on:
  push:
    branches: [ main, ci-** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Tidy modules
        run: |
          go mod tidy
          git diff --exit-code || (echo "go.mod/go.sum not tidy" && exit 1)

      - name: Install tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.3

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1

      - name: Vet
        run: go vet ./...

      - name: Test (race)
        run: go test ./... -race -count=1

      - name: Swagger regen must be clean
        run: |
          ~/go/bin/swag init -g cmd/pulse/main.go --parseDependency --parseInternal --generatedTime=false
          git diff --exit-code docs/ || (echo "Swagger regeneration produced diffs" && exit 1)
